BEGIN;

-- 1. Add generated internal identifiers without removing the legacy keys yet.
ALTER TABLE order_purchase
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE order_production
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS purchase_order_id BIGINT;

ALTER TABLE order_product
    ADD COLUMN IF NOT EXISTS production_id BIGINT;

-- 2. Backfill the new relationships through the legacy purchase_id values.
UPDATE order_production production
SET purchase_order_id = purchase.id
FROM order_purchase purchase
WHERE production.purchase_id = purchase.purchase_id
  AND production.purchase_order_id IS NULL;

UPDATE order_product product
SET production_id = production.id
FROM order_production production
WHERE product.purchase_id = production.purchase_id
  AND product.production_id IS NULL;

-- 3. Drop legacy foreign keys and primary keys by column, independent of generated names.
DO $$
DECLARE constraint_name TEXT;
BEGIN
    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
        WHERE t.relname = 'order_product' AND a.attname = 'purchase_id' AND c.contype = 'f'
    LOOP EXECUTE format('ALTER TABLE order_product DROP CONSTRAINT %I', constraint_name); END LOOP;

    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
        WHERE t.relname = 'order_production' AND a.attname = 'purchase_id' AND c.contype = 'f'
    LOOP EXECUTE format('ALTER TABLE order_production DROP CONSTRAINT %I', constraint_name); END LOOP;

    FOR constraint_name IN
        SELECT c.conname FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'order_purchase' AND c.contype = 'p'
    LOOP EXECUTE format('ALTER TABLE order_purchase DROP CONSTRAINT %I', constraint_name); END LOOP;

    FOR constraint_name IN
        SELECT c.conname FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'order_production' AND c.contype = 'p'
    LOOP EXECUTE format('ALTER TABLE order_production DROP CONSTRAINT %I', constraint_name); END LOOP;
END $$;

-- 4. Enforce the new keys and relationships.
ALTER TABLE order_purchase
    ALTER COLUMN id SET NOT NULL,
    ADD CONSTRAINT pk_order_purchase PRIMARY KEY (id),
    ADD CONSTRAINT uk_order_purchase_purchase_id UNIQUE (purchase_id);

ALTER TABLE order_production
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN purchase_order_id SET NOT NULL,
    ADD CONSTRAINT pk_order_production PRIMARY KEY (id),
    ADD CONSTRAINT uk_order_production_purchase_order UNIQUE (purchase_order_id),
    ADD CONSTRAINT fk_order_production_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES order_purchase(id) ON DELETE CASCADE;

ALTER TABLE order_product
    ALTER COLUMN production_id SET NOT NULL,
    ADD CONSTRAINT fk_order_product_production
        FOREIGN KEY (production_id) REFERENCES order_production(id) ON DELETE CASCADE;

-- 5. Remove the old mutable-string relationship columns.
ALTER TABLE order_product DROP COLUMN purchase_id;
ALTER TABLE order_production DROP COLUMN purchase_id;

COMMIT;
